export const appTypes = {
  REQUEST_DATA_START: "REQUEST_DATA_START",
  REQUEST_DATA_FAILURE: "REQUEST_DATA_FAILURE",
  REQUEST_DATA_SUCCESS: "REQUEST_DATA_SUCCESS",
  HANDLE_ERROR: "HANDLE_ERROR",
  FORCE_AUTH: "FORCE_AUTH"
};
