export const assetTypes = {
  RETREIVE_ASSETS_SUCCESS: "RETREIVE_ASSETS_SUCCESS",
  RETREIVE_ASSETS_FAILURE: "RETREIVE_ASSETS_FAILURE",
  RETREIVE_ASSET_SUCCESS: "RETREIVE_ASSET_SUCCESS",
  RETREIVE_ASSET_FAILURE: "RETREIVE_ASSET_FAILURE",
  UPDATE_ASSET_REQUEST: "UPDATE_ASSET_REQUEST",
  UPDATE_ASSET_SUCCESS: "UPDATE_ASSET_SUCCESS",
  UPDATE_ASSET_FAILURE: "UPDATE_ASSET_FAILURE",
  UPLOAD_ASSET_REQUEST: "UPLOAD_ASSET_REQUEST",
  UPLOAD_ASSET_SUCCESS: "UPLOAD_ASSET_SUCCESS",
  UPLOAD_ASSET_FAILURE: "UPLOAD_ASSET_FAILURE",
  CREATE_ASSET_REQUEST: "CREATE_ASSET_REQUEST",
  CREATE_ASSET_SUCCESS: "CREATE_ASSET_SUCCESS",
  CREATE_ASSET_FAILURE: "CREATE_ASSET_FAILURE",
  DELETE_ASSET_REQUEST: "DELETE_ASSET_REQUEST",
  DELETE_ASSET_SUCCESS: "DELETE_ASSET_SUCCESS",
  DELETE_ASSET_FAILURE: "DELETE_ASSET_FAILURE",
  ASSETS_API: {
    LIST_ASSETS_URL: () => `${process.env.REACT_APP_API_URL}/asset/all`,
    UPDATE_ASSET_URL: uuid => `${process.env.REACT_APP_API_URL}/asset/${uuid}`,
    UPLOAD_ASSET_URL: uuid =>
      `${process.env.REACT_APP_API_URL}/asset/${uuid}/upload`,
    DELETE_ASSET_URL: uuid => `${process.env.REACT_APP_API_URL}/asset/${uuid}`,
    RETREIVE_ASSET_URL: uuid =>
      `${process.env.REACT_APP_API_URL}/asset/${uuid}`,
    CREATE_ASSET_URL: () => `${process.env.REACT_APP_API_URL}/asset`
  }
};
