export const postTypes = {
  RETREIVE_POSTS_SUCCESS: "RETREIVE_POSTS_SUCCESS",
  RETREIVE_POSTS_FAILURE: "RETREIVE_POSTS_FAILURE",
  RETREIVE_POST_SUCCESS: "RETREIVE_POST_SUCCESS",
  RETREIVE_POST_FAILURE: "RETREIVE_POST_FAILURE",
  UPDATE_POST_REQUEST: "UPDATE_POST_REQUEST",
  UPDATE_POST_SUCCESS: "UPDATE_POST_SUCCESS",
  UPDATE_POST_FAILURE: "UPDATE_POST_FAILURE",
  CREATE_POST_REQUEST: "CREATE_POST_REQUEST",
  CREATE_POST_SUCCESS: "CREATE_POST_SUCCESS",
  CREATE_POST_FAILURE: "CREATE_POST_FAILURE",
  PUBLISH_POST_REQUEST: "PUBLISH_POST_REQUEST",
  PUBLISH_POST_SUCCESS: "PUBLISH_POST_SUCCESS",
  PUBLISH_POST_FAILURE: "PUBLISH_POST_FAILURE",
  ARCHIVE_POST_REQUEST: "ARCHIVE_POST_REQUEST",
  ARCHIVE_POST_SUCCESS: "ARCHIVE_POST_SUCCESS",
  ARCHIVE_POST_FAILURE: "ARCHIVE_POST_FAILURE",
  DELETE_POST_REQUEST: "DELETE_POST_REQUEST",
  DELETE_POST_SUCCESS: "DELETE_POST_SUCCESS",
  DELETE_POST_FAILURE: "DELETE_POST_FAILURE",
  POSTS_API: {
    LIST_POSTS_URL: () => `${process.env.REACT_APP_API_URL}/post/all`,
    UPDATE_POST_URL: uuid => `${process.env.REACT_APP_API_URL}/post/${uuid}`,
    DELETE_POST_URL: uuid => `${process.env.REACT_APP_API_URL}/post/${uuid}`,
    RETREIVE_POST_URL: uuid => `${process.env.REACT_APP_API_URL}/post/${uuid}`,
    PUBLISH_POST_URL: uuid =>
      `${process.env.REACT_APP_API_URL}/post/${uuid}/publish`,
    ARCHIVE_POST_URL: uuid =>
      `${process.env.REACT_APP_API_URL}/post/${uuid}/archive`,
    CREATE_POST_URL: () => `${process.env.REACT_APP_API_URL}/post`
  }
};
